---

- hosts: all
  sudo: yes

  vars:
    varjocafe_home: /opt/varjocafe
    varjocafe_port: 8001
    nginx_varjocafe_cache: /var/cache/nginx/varjocafe
    primary_domain: varjocafe.net
    secondary_domain: www.varjocafe.net
    open_tcp_ports:
      - 80

  tasks:
    # selinux
    - name: Install libselinux-python
      yum: name=libselinux-python

    - name: Install policycoreutils-python
      yum: name=policycoreutils-python

    - name: Allow nginx to work as a proxy
      seboolean: name=httpd_can_network_connect state=yes persistent=yes

    # epel
    - name: Add EPEL repository
      yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

    # firewall
    - name: Install ferm
      yum: name=ferm

    - name: Configure ferm
      template:
        src: templates/ferm.conf.j2
        dest: /etc/ferm.conf
        owner: root
        group: root
        mode: 0600

    - name: Configure iptables with ferm
      command: /usr/sbin/ferm /etc/ferm.conf

    - name: Start iptables
      service: name=iptables state=started enabled=yes

    - name: Save current iptables configuration
      command: service iptables save

    # nginx
    - name: Add nginx repository
      yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

    - name: Install nginx
      yum: name=nginx

    - name: Remove example configuration
      file:
        path: /etc/nginx/conf.d/{{ item }}
        state: absent
      with_items:
        - default.conf
        - example_ssl.conf

    - name: Start nginx
      service: name=nginx state=started enabled=yes

    # supervisord
    - name: Install supervisord
      yum: name=supervisor

    - name: Start supervisord
      service: name=supervisord state=started enabled=yes

    # varjocafe
    - name: Install java
      yum: name=java-1.8.0-openjdk

    - name: Create varjocafe user
      user:
        name: varjocafe
        system: yes
        shell: /sbin/nologin
        home: "{{ varjocafe_home }}"
        createhome: no

    - name: Create varjocafe home directory
      file:
        path: "{{ varjocafe_home }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy varjocafe settings
      template:
        src: templates/varjocafe.properties.j2
        dest: "{{ varjocafe_home }}/varjocafe.properties"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart supervisord

    - name: Copy varjocafe binary
      copy:
        src: ../target/varjocafe-standalone.jar
        dest: "{{ varjocafe_home }}/varjocafe-standalone.jar"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart supervisord

    - name: Configure supervisord
      ini_file:
        dest: /etc/supervisord.conf
        section: program:varjocafe
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict:
        command: sh -c "cd {{ varjocafe_home }} && TZ='Europe/Helsinki' exec java -jar varjocafe-standalone.jar"
        user: varjocafe
        logfile: /var/log/supervisor/varjocafe.log
        log_stdout: "true"
        log_stderr: "true"
        autorestart: "true"
        startsecs: 10
      notify:
        - restart supervisord

    - name: Create nginx cache directory
      file:
        path: "{{ nginx_varjocafe_cache }}"
        state: directory
        owner: nginx
        group: root
        mode: 0700

    - name: Configure nginx
      template:
        src: templates/nginx-varjocafe.conf.j2
        dest: /etc/nginx/conf.d/varjocafe.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart supervisord
      service: name=supervisord state=restarted
