---

- hosts: all
  sudo: yes

  vars:
    varjocafe_home: /opt/varjocafe
    varjocafe_port: 8001
    nginx_varjocafe_cache: /var/cache/nginx/varjocafe
    primary_domain: varjocafe.net
    secondary_domain: www.varjocafe.net
    open_tcp_ports:
      - 80

  tasks:
    # selinux
    - name: install libselinux-python
      yum: name=libselinux-python

    - name: install policycoreutils-python
      yum: name=policycoreutils-python

    - name: allow nginx to work as a proxy
      seboolean: name=httpd_can_network_connect state=yes persistent=yes

    # epel
    - name: add EPEL repository
      yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

    # firewall
    - name: install ferm
      yum: name=ferm

    - name: configure ferm
      template:
        src: templates/ferm.conf.j2
        dest: /etc/ferm.conf
        owner: root
        group: root
        mode: 0600

    - name: configure iptables with ferm
      command: /usr/sbin/ferm /etc/ferm.conf

    - name: iptables is running and enabled
      service: name=iptables state=started enabled=yes

    - name: persist this iptables configuration across reboots
      command: service iptables save

    # nginx
    - name: add nginx repository
      yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

    - name: install nginx
      yum: name=nginx

    - name: create nginx cache directory for varjocafe
      file:
        path: "{{ nginx_varjocafe_cache }}"
        state: directory
        owner: nginx
        group: root
        mode: 0700

    - name: configure nginx
      template:
        src: templates/nginx/default.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart nginx

    - name: start nginx
      service: name=nginx state=started enabled=yes

    # supervisord
    - name: install supervisord
      yum: name=supervisor

    - name: configure supervisord
      template:
        src: templates/supervisord.conf.j2
        dest: /etc/supervisord.conf
        owner: root
        group: root
        mode: 0644

    - name: start supervisord
      service: name=supervisord state=started enabled=yes

    # varjocafe
    - name: install java
      yum: name=java-1.8.0-openjdk

    - name: create varjocafe user
      user:
        name: varjocafe
        system: yes
        shell: /sbin/nologin
        home: "{{ varjocafe_home }}"
        createhome: no

    - name: create varjocafe home directory
      file:
        path: "{{ varjocafe_home }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: create varjocafe log directory
      file:
        path: "{{ varjocafe_home }}/log"
        state: directory
        owner: varjocafe
        group: root
        mode: 0750

    - name: copy varjocafe startup script
      template:
        src: templates/varjocafe/start.sh.j2
        dest: "{{ varjocafe_home }}/start.sh"
        owner: root
        group: root
        mode: 0755

    - name: copy varjocafe shutdown script
      template:
        src: templates/varjocafe/stop.sh.j2
        dest: "{{ varjocafe_home }}/stop.sh"
        owner: root
        group: root
        mode: 0755

    - name: copy varjocafe settings
      template:
        src: templates/varjocafe/varjocafe.properties.j2
        dest: "{{ varjocafe_home }}/varjocafe.properties"
        owner: root
        group: root
        mode: 0644

    - name: copy varjocafe binary
      copy:
        src: ../target/varjocafe-standalone.jar
        dest: "{{ varjocafe_home }}/varjocafe-standalone.jar"
        owner: root
        group: root
        mode: 0644

    - name: restart varjocafe
      command: "{{ varjocafe_home }}/start.sh chdir={{ varjocafe_home }}"
      sudo: yes
      sudo_user: varjocafe

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
